[versions]
clikt = "3.5.2"
fastutil = "8.5.12"
guava = "31.1-jre"
guice = "5.1.0"
inline-logger = "1.0.4"
jackson = "2.14.2"
jmh = "0.7.0"
junit = "5.9.2"
kotlin-coroutines = "1.7.0-Beta"
kotlin-poet = "1.12.0"
kotlin-script = "1.8.20-RC2"
kotlinter = "3.14.0"
logback = "1.4.5"
netty = "4.1.87.Final"
openrs2 = "0.1.0-SNAPSHOT"
manes-versions = "0.46.0"

[plugins]
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh" }
versions = { id = "com.github.ben-manes.versions", version.ref = "manes-versions" }

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
inlineLogger = { module = "com.michael-bull.kotlin-inline-logger:kotlin-inline-logger-jvm", version.ref = "inline-logger" }
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jacksonKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jacksonToml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson" }
junitApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junitParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
kotlinCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlinCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlin-poet" }
kotlinScriptRuntime = { module = "org.jetbrains.kotlin:kotlin-script-runtime", version.ref = "kotlin-script" }
kotlinScriptCommon = { module = "org.jetbrains.kotlin:kotlin-scripting-common", version.ref = "kotlin-script" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
nettyBuffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
nettyCodecCore = { module = "io.netty:netty-codec", version.ref = "netty" }
nettyHandler = { module = "io.netty:netty-handler", version.ref = "netty" }
nettyTransport = { module = "io.netty:netty-transport", version.ref = "netty" }
openrs2Buffer = { module = "org.openrs2:openrs2-buffer", version.ref = "openrs2" }
openrs2Cache = { module = "org.openrs2:openrs2-cache", version.ref = "openrs2" }
openrs2Crypto = { module = "org.openrs2:openrs2-crypto", version.ref = "openrs2" }
