[versions]
apache-commons = "1.18.0"
argon2-jvm = "2.12"
bouncycastle = "1.80"
classgraph = "4.8.179"
clikt = "5.0.3"
fastutil = "8.5.15"
flyway = "9.22.3"
gradle-download = "5.6.0"
guice = "7.0.0"
inline-logger = "1.0.6"
jackson = "2.18.3"
jmh = "1.37"
jmh-gradle-plugin = "0.7.2"
junit = "5.11.4"
konsist = "0.16.1"
kotlin = "2.1.20"
kotlin-coroutines = "1.10.1"
logback = "1.5.18"
manes-versions = "0.52.0"
netty = "4.1.109.Final"
okhttp = "5.0.0-alpha.14"
otp-kotlin = "2.4.1"
openrs2 = "0.1.0-SNAPSHOT"
rsprot = "1.0.0-ALPHA-20250409"
spotless = "7.0.2"
sqlite = "3.49.1.0"

[libraries]
apache-commons = { module = "commons-codec:commons-codec", version.ref = "apache-commons" }
argon2-jvm = { module = "de.mkammerer:argon2-jvm", version.ref = "argon2-jvm" }
bouncycastle-provider = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "fastutil" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-toml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jmh-gradle-plugin = { module = "me.champeau.jmh:jmh-gradle-plugin", version.ref = "jmh-gradle-plugin" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-inline-logger = { module = "com.michael-bull.kotlin-inline-logger:kotlin-inline-logger", version.ref = "inline-logger" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
netty-buffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
otp-kotlin = { module = "dev.turingcomplete:kotlin-onetimepassword", version.ref = "otp-kotlin" }
openrs2-buffer = { module = "org.openrs2:openrs2-buffer", version.ref = "openrs2" }
openrs2-cache = { module = "org.openrs2:openrs2-cache", version.ref = "openrs2" }
rsprot-api = { module = "net.rsprot:osrs-229-api", version.ref = "rsprot" }
rsprot-shared = { module = "net.rsprot:osrs-229-shared", version.ref = "rsprot" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }

[bundles]
logging = ["logback-classic", "kotlin-inline-logger"]

[plugins]
gradle-download = { id = "de.undercouch.download", version.ref = "gradle-download" }
manes-versions = { id = "com.github.ben-manes.versions", version.ref = "manes-versions" }
